fix: prevent opening new tab when invoking function and show notification (#141)
redhat-developer/intellij-knative pull request #142
Opened 2022-04-07 14:03 UTC by lstocchi

it resolves #141 

![image](https://user-images.githubusercontent.com/49404737/162217563-fa536e7c-afb1-4c32-a253-cf211d65077f.png)

2022-04-11 09:26 UTC, jeffmaury approved these changes
LGTM but what is the reason the invoke output is not visible to the user. There are some cases where I think it might be usefull (async invocation where you need to know the execution id)

2022-04-11 09:36 UTC, lstocchi commented
> LGTM but what is the reason the invoke output is not visible to the user. There are some cases where I think it might be usefull (async invocation where you need to know the execution id)

TBH i didn't think about the ID and you're right, it can be useful to know it. 

Initially I removed the tab because it just prints out the same things the user see/write in the wizard to invoke the function so it looked to me as a duplicate. But the ID is effectively not shown. Maybe showing the generated ID in the notification is enough? WDYT?

cc @mohitsuman

2022-04-11 09:41 UTC, jeffmaury commented
Yes but does it requires to parse the non structured output because it is error prone. If we have JSON output to retrieve the ID then I'm +1

2022-04-11 10:52 UTC, lstocchi commented
@jeffmaury latest cli 0.23.0 returns a JSON. I rebased this PR and used the newest cli. -> https://github.com/redhat-developer/intellij-knative/pull/142/commits/79d74ac9409d1bdf16d87e410d14dd093dd3ec9a

2022-04-11 11:43 UTC, jeffmaury requested changes
LGTM

2022-04-11 11:43 UTC, jeffmaury commented on src/main/java/com/redhat/devtools/intellij/knative/actions/func/InvokeAction.java
> +                            "Function " + name + " has been successfully invoked with execution id " + id + " !",
If by mistake id is not found in the JSON output, an empty string is returned thus we should handle this case to gererate proper information/notification to the user

2022-04-14 07:06 UTC, jeffmaury approved these changes
LGTM

2022-04-14 10:02 UTC, merged