chore: prepare for 1.3.0
redhat-developer/intellij-knative pull request #217
Opened 2022-10-21 09:59 UTC by lstocchi

2022-10-21 15:59 UTC, mohitsuman approved these changes

2022-10-24 06:34 UTC, jeffmaury requested changes

2022-10-24 06:34 UTC, jeffmaury commented on README.md
> +It is possible to start an on-cluster build from the IDE. The action is enabled if Knative and Tekton are both installed
Maybe we should explain what is on cluster build ? What is does exactly ?

2022-10-24 08:01 UTC, jeffmaury approved these changes
LGTM

2022-10-24 08:32 UTC, merged