chore(skip-release):bump sinceIdea to 2022.3
redhat-developer/intellij-knative pull request #250
Opened 2024-04-11 09:07 UTC by adietish

2024-04-12 09:55 UTC, sbouchet requested changes

2024-04-12 09:55 UTC, sbouchet commented on .github/workflows/IJ.yml
> +        IJ: [IU-2022.3, IU-2023.1, IU-2023.2, IU-2024.1]
IU-2023.3 is missing

2024-04-12 15:06 UTC, sbouchet commented on .github/workflows/IJ.yml
> +        IJ: [IU-2022.3, IU-2023.1, IU-2023.2, IU-2023.2, IU-2024.1]
```suggestion
        IJ: [IU-2022.3, IU-2023.1, IU-2023.2, IU-2023.3, IU-2024.1]
```

2024-04-12 15:07 UTC, sbouchet requested changes
still a typo

2024-04-15 12:34 UTC, adietish commented
@sbouchet: ready to merge?

2024-04-15 14:41 UTC, sbouchet approved these changes
LGTM

2024-04-15 14:47 UTC, merged